package edu.uark.registerapp.commands.employees;

import java.util.Optional;

import javax.transaction.Transactional;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import edu.uark.registerapp.commands.ResultCommandInterface;
import edu.uark.registerapp.commands.exceptions.ConflictException;
import edu.uark.registerapp.commands.exceptions.UnprocessableEntityException;
import edu.uark.registerapp.models.api.Employee;
import edu.uark.registerapp.models.entities.EmployeeEntity;
import edu.uark.registerapp.models.repositories.EmployeeRepository;

@Service
public class EmployeeCreateCommand implements ResultCommandInterface<Employee> {
	@Override
	public Employee execute() {
		this.validateProperties();

		final EmployeeEntity createdEmployeeEntity = this.createEmployeeEntity();

		// Synchronize information generated by the database upon INSERT.
		this.apiEmployee.setId(createdEmployeeEntity.getId()); 
		this.apiEmployee.setCreatedOn(createdEmployeeEntity.getCreatedOn());

		return this.apiEmployee;
	}

	// Helper methods
	private void validateProperties() {
		if (StringUtils.isBlank(this.apiEmployee.getLookupCode())) {
			throw new UnprocessableEntityException("lookupcode");
		}
	}
	public void validateEmployee(){
		Employee employee = this.getApiEmployee();

		if(employee.getFirstName().isEmpty()){
			throw new UnprocessableEntityException("First Name cannot be blank");
		}

		if(employee.getLastName().isEmpty()){
			throw new UnprocessableEntityException("Last Name cannot be blank");
		}

		if(employee.getPassword().isEmpty()){
			throw new UnprocessableEntityException("Password cannot be blank");
		}
	}

	public void setDefaultsForEmployee(){
		Employee employee =this.getApiEmployee();

		if (this.IsInitialEmployee()){
			//general manager
		}
	}

	@Transactional
	private EmployeeEntity createEmployeeEntity() {
		final Optional<EmployeeEntity> queriedEmployeeEntity =
			this.EmployeeRepository
				.findByLookupCode(this.apiEmployee.getLookupCode());

		if (queriedEmployeeEntity.isPresent()) {
			// Lookupcode already defined for another Employee.
			throw new ConflictException("lookupcode");
		}

		// No ENTITY object was returned from the database, thus the API object's
		// lookupcode must be unique.

		// Write, via an INSERT, the new record to the database.
		return this.EmployeeRepository.save(
			new EmployeeEntity(apiEmployee));
	}

	// Properties
	private Employee apiEmployee;
	private boolean setIsInitialEmployeeFlag;

	public Employee getApiEmployee() {
		return this.apiEmployee;
	}

	public EmployeeCreateCommand setApiEmployee(final Employee apiEmployee) {
		this.apiEmployee = apiEmployee;
		return this;
	}
	public void setIsInitialEmployee(bool IsInitialEmployee){
		this.IsInitialEmployeeFlag = IsInitialEmployee;
	}
	public boolean sIsInitialEmployee(){
		return this.sIsInitialEmployeeFlag;
	}

	@Autowired
	private EmployeeRepository EmployeeRepository;
}
